default: &default
  adapter: postgresql
  host: localhost
  username: annapetry
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development

production:
  <<: *default
  database: db/production
