# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 090d6445b01669d98c6655fa1466a4af5513e77ff85eeb9f703576e88ce497b8330083e585bac398b48f26072dc026e284b96ca6157211d404456f5f45a85394

test:
  secret_key_base: 2641b168a4805973b9d9883e569b1834cb04488d85eb7702f14222301105ddd235fcd67a6245132c80ae5dfa50b210fa884517d6b0dced17e759f43821a36c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
